stages:
  - build

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "1"

docker:
  image: docker:latest
  stage: build
  tags:
    - 'docker-build'
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE} .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master

docker-release:
  image: docker:latest
  stage: build
  tags:
    - 'docker-build'
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags
